## Getting GDP and Cleaning##
we used the following link for GDP:
$$
$$
https://www.worldometers.info/gdp/gdp-by-country/
$$
$$
Frm here we load the data and launch it

In [7]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import scipy as sci
from requests import get

In [8]:
url = 'https://www.worldometers.info/gdp/gdp-by-country/'

In [9]:
response=get(url)
soup=BeautifulSoup(response.text,'html.parser')

In [10]:
Head=soup.find('thead')
H=Head.find_all('th')
Table=soup.find('tbody')
T=Table.find_all('tr')
columns=[col for col in T[0]]
Beep=[T[i] for i in range(0,len(T))]
headers=[i.get_text() for i in H]
headers

['#',
 'Country',
 'GDP (nominal, 2017) ',
 'GDP (abbrev.)',
 'GDP  growth',
 'Population (2017) ',
 'GDP  per capita ',
 'Share of World GDP ']

In [11]:
tipping=[]
for col in columns:
    if col==' ':
        pass
    else:
        tipping.append(col.get_text())

In [12]:
tip=[]
for i in range(0,len(T)):
    clip=[]
    columns=[col for col in T[i]]
    for col in columns:
        if col==' ':
            pass
        else:
            clip.append(col.get_text())
    tip.append(clip)
gdp=pd.DataFrame(tip,columns=headers)
gdp

,#,Country,"GDP (nominal, 2017)",GDP (abbrev.),GDP growth,Population (2017),GDP per capita,Share of World GDP
0,1,United States,"$19,485,394,000,000",$19.485 trillion,2.27%,"325,084,756","$59,939",24.08%
1,2,China,"$12,237,700,479,375",$12.238 trillion,6.90%,"1,421,021,791","$8,612",15.12%
2,3,Japan,"$4,872,415,104,315",$4.872 trillion,1.71%,"127,502,725","$38,214",6.02%
3,4,Germany,"$3,693,204,332,230",$3.693 trillion,2.22%,"82,658,409","$44,680",4.56%
4,5,India,"$2,650,725,335,364",$2.651 trillion,6.68%,"1,338,676,785","$1,980",3.28%
...,...,...,...,...,...,...,...,...
184,185,Sao Tome & Principe,"$392,570,293",$393 million,3.87%,"207,089","$1,896",0.00%
185,186,Palau,"$289,823,500",$290 million,-3.57%,"17,808","$16,275",0.00%
186,187,Marshall Islands,"$204,173,430",$204 million,3.60%,"58,058","$3,517",0.00%
187,188,Kiribati,"$185,572,502",$186 million,0.33%,"114,158","$1,626",0.00%
188,189,Tuvalu,"$39,731,317",$40 million,3.24%,"11,370","$3,494",0.00%

In [13]:
#cleaning GDP nominal
gdp['GDP (nominal, 2017) ']=gdp['GDP (nominal, 2017) '].str.replace('$',' ')
gdp['GDP (nominal, 2017) ']=gdp['GDP (nominal, 2017) '].str.replace(',','').astype(float)
gdp['GDP (nominal, 2017) ']=pd.to_numeric(gdp['GDP (nominal, 2017) '] )
gdp.rename(columns={'GDP (nominal, 2017) ':'GDP($)'}, inplace=True)

In [15]:
#Cleanng GDP abbrev
gdp['GDP (abbrev.)']=gdp['GDP (abbrev.)'].str.replace('$',' ')
def money(num,part):
    if part=='trillion':
        num=num*1000000000000
    elif part=='billion':
        num=num*1000000000
    else:
        num=num*1000000
    return(num)

def marker(plop):
    mak=len(plop)//2
    num=plop[0:mak]
    word=plop[mak:len(plop)]
    if word=='illion' or word=='rillion' :
        num=float(plop[0:mak-1])
        word=plop[mak-1:len(plop)]
        return(money(num,word))
    else:
        return(money(float(num),word))
gdp['GDP (abbrev.)']=[marker(i) for i in gdp['GDP (abbrev.)']]
gdp.rename(columns={'GDP (abbrev.)':'GDP (abbrev.)($)'}, inplace=True)

KeyError: 'GDP (abbrev.)'

In [16]:
#clean growth
gdp['GDP  growth']=gdp['GDP  growth'].str.replace('%','').astype(float).divide(100)
gdp.rename(columns={'GDP  growth':'GDP  growth(%)'}, inplace=True)
#clean population
gdp['Population (2017) ']=gdp['Population (2017) '].str.replace(',','').astype(int)
gdp.rename(columns={'Population (2017) ':'Population'}, inplace=True)
#clean per capita
gdp['GDP  per capita ']=gdp['GDP  per capita '].str.replace('$',' ').str.replace(',','').astype(int)
gdp.rename(columns={'GDP  per capita ':'GDP  per capita ($)'}, inplace=True)
#share of GDP
gdp['Share of World GDP ']=gdp['Share of World GDP '].str.replace('%','').astype(float).divide(100)
gdp.rename(columns={'Share of World GDP ':'Share of World GDP (%)'}, inplace=True)

In [17]:
gdp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 189 entries, 0 to 188
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   #                       189 non-null    object
 1   Country                 189 non-null    object
 2   GDP($)                  189 non-null    float64
 3   GDP (abbrev.)($)        189 non-null    float64
 4   GDP  growth(%)          189 non-null    float64
 5   Population              189 non-null    int32
 6   GDP  per capita ($)     189 non-null    int32
 7   Share of World GDP (%)  189 non-null    float64
dtypes: float64(4), int32(2), object(2)
memory usage: 10.5+ KB

In [18]:
gdp

,#,Country,GDP($),GDP (abbrev.)($),GDP growth(%),Population,GDP per capita ($),Share of World GDP (%)
0,1,United States,1.948539e+13,1.948500e+13,0.0227,325084756,59939,0.2408
1,2,China,1.223770e+13,1.223800e+13,0.0690,1421021791,8612,0.1512
2,3,Japan,4.872415e+12,4.872000e+12,0.0171,127502725,38214,0.0602
3,4,Germany,3.693204e+12,3.693000e+12,0.0222,82658409,44680,0.0456
4,5,India,2.650725e+12,2.651000e+12,0.0668,1338676785,1980,0.0328
...,...,...,...,...,...,...,...,...
184,185,Sao Tome & Principe,3.925703e+08,3.930000e+08,0.0387,207089,1896,0.0000
185,186,Palau,2.898235e+08,2.900000e+08,-0.0357,17808,16275,0.0000
186,187,Marshall Islands,2.041734e+08,2.040000e+08,0.0360,58058,3517,0.0000
187,188,Kiribati,1.855725e+08,1.860000e+08,0.0033,114158,1626,0.0000
188,189,Tuvalu,3.973132e+07,4.000000e+07,0.0324,11370,3494,0.0000